version: '3.7'

services:
  reverse_nginx:
    container_name: reverse_nginx
    hostname: reverse_nginx
    image: nginx:1.22.0-alpine
    networks:
      - reverse
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./flask-app/static:/usr/share/nginx/html/static
      - ./flask-app/templates:/usr/share/nginx/html
    restart: always
  flask_app:
    image: flask_app_image:1.0
    container_name: flask_app
    networks:
      - elastic
      - reverse
    depends_on:
      - reverse_nginx
      - es
    restart: always
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: es
    environment:
      - discovery.type=single-node
    volumes:
      - data_es:/usr/share/elasticsearch/data
    networks:
      - elastic
    depends_on:
      - reverse_nginx
    restart: always

volumes:
  data_es:
    driver: local

networks:
  elastic:
    driver: bridge
  reverse:
    driver: bridge